const Images = {
    img_edf_pqñ_2: 'edificios_pequeños_2_asm6eh',
    img_edf_pqñ_3: 'edificios_pequeños_3_gq1tqp',
    img_edf_pqñ_4: 'edificios_medianos_7_pqdog6',
    img_edf_pqñ_5: 'edificios_pequeños_7_rnplzo',
    img_edf_pqñ_6: 'edificios_pequeños_6_pzldk4',
    img_edf_pqñ_7: 'edificios_pequeños_8_wyac1z',
    img_edf_med_1: 'edificios_medianos_10_scqglb',
    img_edf_med_2: 'edificios_medianos_10_scqglb',
    img_edf_med_3: 'edificios_medianos_8_tqnh7o',
    img_edf_med_4: 'edificios_medianos_4_doudjy',
    img_edf_med_5: 'edificios_medianos_5_c4wapy',
    img_edf_med_6: 'edificios_medianos_6_vnsib1',
    img_edf_med_7: 'edificios_medianos_3_ukseim',
    img_edf_med_8: 'edificios_grandes_17_guezvc',
    img_edf_med_9: 'edificio_mediano_2_qckuoj',
    img_edf_med_10: 'edificio_mediano_ojsxaj',
    img_edf_grn_1: 'edificios_grandes_16_lw8uiu',
    img_edf_grn_2: 'edificios_grandes_14_kxkoq8',
    img_edf_grn_3: 'edificios_grandes_15_ngdcwd',
    img_edf_grn_4: 'edificios_grandes_13_ja4hlb',
    img_edf_grn_5: 'edificios_grandes_13_2_d6lfjz',
    img_edf_grn_6: 'edificios_grande_2_i2k7xz',
    img_edf_grn_7: 'edificios_grandes_3_pjrgyh',
    img_edf_grn_8: 'edificios_grandes_6_lwf08l',
    img_edf_grn_9: 'edificios_grandes_5_mkuo7u',
    img_edf_grn_10: 'edificios_grandes_5_mkuo7u',
    img_edf_grn_11: 'edificio_grande_dm2gjo',
    img_edf_grn_12: 'eddificios_grandes_10_rf4ih9',
    ahorro_tiempo_1: 'ahorro_de_tiempo_2_rferzr',
    ahorro_tiempo_2: 'ahorro_de_tiempo_tzxoln',
    co_work_1: 'close-up-businessman-businesswoman-holding-documents-standing-front-building_ya20uy',
    co_work_3: 'cumplimiento_normativo_mlrmbh',
};

export default Images;

export type ImageName = keyof typeof Images;
